# .github/workflows/playwright.yml

name: Playwright Tests

on:
  push:
    branches: [ main, master ] # Run on push to main or master branch
  pull_request:
    branches: [ main, master ] # Run on pull requests to main or master

jobs:
  test:
    timeout-minutes: 60 # Set a timeout for the entire job
    runs-on: ubuntu-latest # Specify the operating system for the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20 # Or your desired Node.js version, e.g., 18, 20, 22

    - name: Install dependencies
      run: npm ci # 'npm ci' is preferred over 'npm install' in CI environments for clean installs

    - name: Install Playwright browsers
      run: npx playwright install --with-deps # Install browsers and their dependencies

    - name: Run Playwright tests
      run: npm test # Command to execute your tests